### ISSUE TITLE
Hex Color Values in the Colors Section

### ISSUE THREAD

**Issue by kayspiegel** [getkirby/panel-ui#3]
The color sections (`1-atoms/1-global/1-colors`) works for some hex values bit not for all. The color code `004e89` for examples prints `4.0E+89` in the front-end. `032636` prints `32636`.

Changing the colors.php from: `<?php echo $color['code'] ?>` to `<?php echo html($color['code']) ?>` did not help. Anybody an idea how to fix this?

![screenshot](https://cloud.githubusercontent.com/assets/6973401/6671058/02286682-cc03-11e4-9c65-85d95b51e766.png)

**Comment by lukasbestle** [comment]
Oh, that looks like exponential notation. Quite funny. :D
It seems like the YAML parser invoked in [colors.php](https://github.com/getkirby/patternlab/blob/master/site/snippets/colors.php#L2) is trying to be smart. Maybe putting the `#` symbol into the content file and removing it from `colors.php` fixes that problem.

**Comment by kayspiegel** [comment]
No, I already tried that one ;-) Adding the `#` to the content kills the colors ;-)

![screenshot2](https://cloud.githubusercontent.com/assets/6973401/6671351/f0a65bce-cc04-11e4-95d7-89ac024029a1.png)

**Comment by lukasbestle** [comment]
Ah, d'oh. `#` begins a comment in YAML.

Another solution: quote the color code using `"`.

**Comment by kayspiegel** [comment]
Nope, didn't work either :-(

**Comment by lukasbestle** [comment]
What's the result this time?

**Comment by kayspiegel** [comment]
Same as using `'`.

**Comment by kayspiegel** [comment]
Argh, my mistake @lukasbestle, adding strings to txt file worked perfectly ... was a hard day yesterday ;-) Thanks for your kind help.
